# Generated by Django 5.2.5 on 2025-09-08 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0002_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="codigo",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
