# Generated by Django 5.2.5 on 2025-09-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0003_alter_curso_codigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estudante",
            old_name="data_nacimento",
            new_name="data_nascimento",
        ),
    ]
