# Generated by Django 5.2.5 on 2025-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0004_rename_data_nacimento_estudante_data_nascimento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudante",
            name="idade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
